# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:OneDrive - Naspers\GithubFolder\NexGenLogGuide\ui_files\about.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from utils import get_version, get_author
class Ui_About(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(550, 350)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 550, 350))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(450, 320, 71, 23))
        self.pushButton.setObjectName("pushButton")
        #self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setOpenExternalLinks(True)
        self.label.setStyleSheet("background-color: white") 
        self.pushButton.clicked.connect(Dialog.close)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "About"))
        initialstr = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"\
                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n" \
                        "p, li { white-space: pre-wrap; }\n" \
                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n" \
                        "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br />\n"

        secondstr = ("<table><tr><td><img src=res\index.png></td><td><H3>NextGenLogGuide - {}<H4>A simple guide for Nexgen decoder logs <br>-Build on 30 August 2020 </H4></H5> </td>Powered by open source software<br>- Python 3.8.3<br>- Pyqt5<br><br><br>Copyright © 2020-2022 {}. All rights reserved.<br>Source code:<a href=\"https://github.com/BharathSundaram/NexGenLogGuide\">github link</a></tr></table> </p></body></html>").format(get_version(), get_author())
        
         
        self.label.setText(_translate("Dialog", (initialstr+secondstr)))
        self.pushButton.setText(_translate("Dialog", "Ok"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_About()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
